# see https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
[target.x86_64-unknown-linux-gnu]
rustflags = "-Clinker=clang -Clink-args=--ld-path=wild"
# see https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
[profile.dev]
debug = 0
strip = "debuginfo"
